spring:
  profiles.active: production

---


info:
  app:
    name: routes-store-service
    description: Provides persistance for routes
    version: 1.0.0
    mode: default

endpoints:
  info:
    enabled: true
    sensitive: false

  health:
    sensitive: false
    
  metrics:
    sensitive: false

server:
    port:     9305

spring:
    profiles: production
    application:
        name: routes-store-service 

eureka:
    client:
        serviceUrl:
            defaultZone:    http://eureka-server:8761/eureka
        healthcheck:
            enabled: true
        instance:
            leaseRenewalIntervalInSeconds: 15
            preferIpAddress:  true

jwtsecurity:
    resourceId: RoutesResourceId
    signingKey: MaYzkSjmkzPC57L    

---
spring:
    profiles: testing

eureka.client.enabled: false     